version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: ghtracker-db
    restart: unless-stopped

    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       github_tracker     

    ports:
      - "5432:5432"                          

    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
